language: node_js
dist: trusty

node_js:
  - "9.8"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - docker-compose -v

before_script:
  - chmod -R o+w ./
  - npm install -g sshpk coveralls

script:
  - make install
  - make ps
  - make test
  - make lint-backend
  - make lint-frontend
  - make build-frontend
  - make stop
  - cat ./coverage/lcov.info | coveralls -v
  - sudo make clean
