sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - docker-compose -v

before_script:
  - mkdir -p client/dist client/tests/e2e/reports
  - ls -al
  - ls -al client
  - ls -al client/tests/e2e

script:
  - make install
  - make ps
  - docker-compose exec frontend ls -al
  - docker-compose exec frontend ls -al tests/e2e
  - make test
  - docker-compose exec frontend ls -al tests/e2e/reports
  - make lint
  - make build-frontend
  - make stop
