language: node_js
dist: trusty

node_js:
  - "9.8"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - docker-compose -v

before_script:
  - chmod -R o+w ./
  - npm install -g codecov coveralls

script:
  - make install
  - make ps
  - make test-api
  - make test-client
  - make lint-api
  - make lint-client
  - make build-client
  - make stop
  - sudo rm -rf .data
  - cat ./api/coverage/lcov.info | coveralls -v
  - codecov
  - sudo make clean
