sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - docker-compose -v

before_script:
  - chmod -R o+w ./

script:
  - make install
  - make ps
  - make test
  - make ci-coverage
  - make lint-backend
  - make lint-frontend
  - make build-frontend
  - make stop
  - make clean
