sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - docker-compose -v

before_script:
  - export NODE_USER=travis

script:
  - make install
  - make ps
  - make test
  - make lint
  - make build-frontend
  - make stop
