sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - docker-compose -v

before_script:
  - mkdir -p client/dist client/tests/e2e/reports
  - chmod o+w client/dist client/tests/e2e/reports

script:
  - make install
  - make ps
  - make test
  - make lint
  - make build-frontend
  - make stop
