coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 5
    patch:
      default:
        target: 50%
        threshold: 5

parsers:
  javascript:
    enable_partials: yes
