version: '3.2'

services:
  backend:
    build:
      context: .
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app:rw,cached
      - backend_node_modules:/usr/src/app/node_modules
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
    ports:
      - "49160:${PORT}"
    command: "npm run dev"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-vue
    volumes:
      - ./client:/usr/src/app:rw,cached
      - frontend_node_modules:/usr/src/app/node_modules
    depends_on:
      - backend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - VUE_APP_API_URL=${VUE_APP_API_URL}
    ports:
      - "8080:8080"
    command: "yarn serve"

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
      args:
        - mongodb_username=${MONGODB_USERNAME}
        - mongodb_password=${MONGODB_PASSWORD}
        - mongodb_database=${MONGO_INITDB_DATABASE}
    volumes:
      - ./.data/mongo:/data/db:rw,cached
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"

volumes:
  backend_node_modules:
  frontend_node_modules:
