FROM node:9-alpine

RUN mkdir -p /usr/src/app

COPY client/package.json client/yarn.lock /usr/src/app/

RUN chown -R node: /usr/src/app

USER node

WORKDIR /usr/src/app

RUN yarn install && yarn cache clean

COPY ./client .
