FROM node:9-stretch

ARG NODE_USER
ENV NODE_USER ${NODE_USER:-node}

ARG CHROME_VERSION="google-chrome-stable"

RUN set -xe \
	&& wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
	&& echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends --no-install-suggests \
		openjdk-8-jdk \
		${CHROME_VERSION:-google-chrome-stable} \
		chromedriver \
	&& rm /etc/apt/sources.list.d/google-chrome.list \
	&& rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN mkdir -p /usr/src/app

COPY client/package.json client/yarn.lock /usr/src/app/

RUN chown -R $NODE_USER: /usr/src/app

USER $NODE_USER

WORKDIR /usr/src/app

RUN yarn install && yarn cache clean

COPY ./client .
