version: '3.2'

services:
  app:
    build:
      context: .
    user: "node"
    volumes:
      - .:/usr/src/app:rw,cached
    environment:
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
    ports:
      - "49160:${PORT}"
    expose:
      - "${PORT}"
    working_dir: /usr/src/app
    command: "npm run dev"
