FROM mongo:3.6

ARG MONGODB_USERNAME
ARG MONGODB_PASSWORD
ARG MONGO_INITDB_DATABASE

COPY mongodb-setup.js /docker-entrypoint-initdb.d/

RUN sed -i -e "s/MONGODB_USERNAME/$MONGODB_USERNAME/g" /docker-entrypoint-initdb.d/mongodb-setup.js
RUN sed -i -e "s/MONGODB_PASSWORD/$MONGODB_PASSWORD/g" /docker-entrypoint-initdb.d/mongodb-setup.js
RUN sed -i -e "s/MONGO_INITDB_DATABASE/$MONGO_INITDB_DATABASE/g" /docker-entrypoint-initdb.d/mongodb-setup.js
