version: '3.2'

services:
  api:
    build:
      context: ./api
      args:
        - TZ=${TZ}
    depends_on:
      - db
    volumes:
      - ./api:/api:rw,cached
      - api_node_modules:/api/node_modules
    restart: always
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DEBUG=${DEBUG}
      - DEBUG_COLORS=${DEBUG_COLORS}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@db:27017/${MONGO_INITDB_DATABASE}
      - MONGODB_URI_TEST=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@db:27017/test
      - NODE_DEBUG_PORT=${NODE_DEBUG_PORT} # used only in "dev" package script
    ports:
      - "49160:${PORT}"
      - "${NODE_DEBUG_PORT}:${NODE_DEBUG_PORT}"
    command: ["./wait-for-mongodb.sh", "yarn run dev"]

  client:
    build:
      context: ./client
    volumes:
      - ./client:/client:rw,cached
      - client_node_modules:/client/node_modules
    depends_on:
      - api
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - TZ=${TZ}
    ports:
      - "8080:8080"
    command: "yarn serve"

  db:
    build:
      context: ./db
    volumes:
      - ./.data/mongo:/data/db:rw,cached
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - TZ=${TZ}
    ports:
      - "27017:27017"

volumes:
  api_node_modules:
  client_node_modules:
