export const ADD_FOO = 'ADD_FOO';
export const UPDATE_FOO_NAME = 'UPDATE_FOO_NAME';
export const FETCH_FOOS = 'FETCH_FOOS';

export const SET_ERROR = 'SET_ERROR';
export const RESET_ERROR = 'RESET_ERROR';

export const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED';
export const SET_USER_UNAUTHENTICATED = 'SET_USER_UNAUTHENTICATED';
export const SET_USER_IS_SIGNING_IN = 'SET_USER_IS_SIGNING_IN';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const SET_EXPIRATION_DATE = 'SET_EXPIRATION_DATE';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
